vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/HostelManagement/tenant/invoices/vnpay-return
vnpay.tmnCode=9J47G09W
vnpay.secretKey=97MPGGLK9UAIP8U69GGZNPNI0KUFVZAN
vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
